pipeline {

    agent any

    environment {
        DEMO_NUMBER = 'DEMO-1.1'
    }

    stages {

        stage('Ok') {

            steps {

                echo "Ok"
            }
        }

        stage('Executing shell script') {

            steps {
                script {

                    cest = TimeZone.getTimeZone("CEST")
                    def cest = new Date()
                    println(cest)
                    def mailRecipients = 'traveldiariesforu@gmail.com'
                    def jobName = currentBuild.fullDisplayName
                    env.Name = Name
                    env.cest = cest
                    emailext body: '''${SCRIPT, template="email-html.template"}''',
                            mimeType: 'text/html',
                            subject: "[Jenkins] ${jobName}",
                            to: "${mailRecipients}",
                            replyTo: "${mailRecipients}"

                }

            }
        }
    }
}

