
pipeline {

    agent any

    environment {
        DEMO_NUMBER = 'DEMO-1.1'
    }

    stages {
        
        stage ('stage-1'){

            agent any
            environment {
                LOCAL_STAGE_ENV_VARIABLE = "SOME_VALUE"
            }

            parallel {

                stage ('parallel 1') {
                    steps {
                        def current_stage = getCurrentStageName()
                        echo "Stage: $current_stage"
                    }
                }

                stage('parallel 2') {
                    steps {
                        def current_stage = getCurrentStageName()
                        echo "Stage: $current_stage"
                    }
                }
                stage('parallel 3') {
                    steps{
                        def current_stage = getCurrentStageName()
                        echo "Stage: $current_stage"
                    }
                }
            }
            steps {
                echo "This is first demo piple #BUILD_NUMBER and $DEMO_NUMBER"
            }
        }

        stage ('stage-2') {

            input {
                     message 'Deploy?'
                     ok 'Do it!'
                     parameters {
                         string (name: 'TARGET_ENVIRONMENT', defaultValue: 'PROD', description: 'Target Deployment Evironment')
                     }
                 }
            steps {
                 echo "Deploying on environment ${TARGET_ENVIRONMENT}"
            }
        }
    }

    post {
        always {
            echo 'Post block is called always'
        }
    }
}

