
pipeline {

    agent any

    environment {
        DEMO_NUMBER = 'DEMO-1.1'
    }

    stages {
        
        stage ('stage-1'){

            // agent is not allowed on stage "stage-1" as it contains parallel or matrix stages
            // agent any
            environment {
                LOCAL_STAGE_ENV_VARIABLE = "SOME_VALUE"
            }

            parallel {

                stage ('parallel 1') {
                    steps {
                        // WorkflowScript: 36: Expected a step @ line 36, column 25
                        echo "Stage: parallel 1"
                    }
                }

                stage('parallel 2') {
                    steps {
                        echo "Stage: parallel 2"
                    }
                }
                stage('parallel 3') {
                    steps{
                        echo "parallel 3"
                    }
                }
            }
        }

        stage ('stage-2') {

            steps {
                 echo "Inside stage-2"
            }
        }
    }

    post {
        always {
            echo 'Post block is called always'
        }
    }
}

