
pipeline {

    agent any

    environment {
        DEMO_NUMBER = 'DEMO-1.1'
    }

    stages {
        
        stage ('stage-1'){

            agent any
            environment {
                LOCAL_STAGE_ENV_VARIABLE = "SOME_VALUE"
            }

            parallel {

                stage ('parallel 1') {
                    steps {
                        def current_stage = getCurrentStageName()
                        echo "Stage: $current_stage"
                    }
                }

                stage('parallel 2') {
                    steps {
                        def current_stage = getCurrentStageName()
                        echo "Stage: $current_stage"
                    }
                }
                stage('parallel 3') {
                    steps{
                        def current_stage = getCurrentStageName()
                        echo "Stage: $current_stage"
                    }
                }
            }
        }

        stage ('stage-2') {

            steps {
                 echo "Inside stage-2"
            }
        }
    }

    post {
        always {
            echo 'Post block is called always'
        }
    }
}

