
pipeline {

    agent any

    environment {
        DEMO_NUMBER = 'DEMO-1.1'
    }

    stages {
        
        stage ('stage-1'){

            steps {
                
                echo "This is first demo piple #BUILD_NUMBER and $DEMO_NUMBER"
            }
        }

        stage ('Executing shell script') {

            steps {
                 
                 sh '''
                    echo "Using multi-line shell script"
                    pwd
                    ls -R
                    ls ./pipeline/basics/simple1
                    chmod +x ./pipeline/basics/simple1/tesh.sh
                    ./pipeline/basics/simple1/tesh.sh
                 '''
            }
        }
    }
}

