
pipeline {

    agent any

    environment {
        DEMO_NUMBER = 'DEMO-1.1'
    }

    stages {
        
        stage ('stage-1'){

            steps {
                
                echo "This is first demo piple $BUILD_NUMBER and $DEMO_NUMBER"
            }
        }

        stage ('Executing shell script') {

            steps {
                 
                 sh '''
                    echo "Using multi-line shell script"
                    pwd
                    ls -R
                    ls ./pipeline/basics/simple1
                    chmod +x ./pipeline/basics/simple1/test.sh
                    ./pipeline/basics/simple1/test.sh

                    ls -l -R ${WORKSPACE}
                 '''
                 echo "Printing environment variable defined in shell" + env.SHELL_VARIABLE
                 echo "This is value of $SHELL_VARIABLE"
            }
        }
    }
}

