pipeline {
    agent any
    environment {
        DEMO_NUMBER = 'DEMO-1.1'
    }
    stages {
        stage ('stage-1'){
            steps {
                echo "This is first demo piple #BUILD_NUMBER and $DEMO_NUMBER"
            }
        }
    }
}

