pipeline {

    agent any

    environment {
        DEMO_NUMBER = 'DEMO-1.1'
    }

    stages {

        stage('Reading environment variable defined in groovy file') {

            environment {
                load "./pipeline/basics/extenvvariable/env.groovy"
            }
            steps {
                echo "${env.env_var1}"
                echo "${env.env_var2}"
            }
        }

        stage('Reading environment variable defined in shell script') {

            environment {
                // environment variables would be initialized in the script file
                LS = "${sh(script: 'chmod +x ./pipeline/basics/extenvvariable/env.sh;./pipeline/basics/extenvvariable/env.sh', returnStdout: true).trim()}"
            }

            steps {

                echo "LS = ${env.ENV_VAR1}"
            }
        }


        stage("Env Variables print") {
            steps {
                sh "printenv"
            }
        }

    }
}

