pipeline {

    agent any
    parameters {
        booleanParam(name: 'RC', defaultValue: false, description: 'This is sample boolean parameter')
    }
    environment {
        VERSION = '0.1.0'
        VERSION_RC = 'rc.2'
    }

    stages {

        stage ('stage1') {
            environment {
                VERSION_SUFFIX = getVersionSuffix()
            }

            steps {
                echo '$VERSION_SUFFIX'
            }
        }

        stage ('simple-sh-execution') {
            steps {
                simpleShExecution()
            }
        }

        stage ('conditional-execution') {
            // when {
            //     expression (return params.RC)
            // }
            steps {
                echo 'execution conditional-execution $BUILD_NUMBER'
            }
        }
    }
}

String getVersionSuffix() {
    if (params.RC) {
        return env.VERSION_RC
    } else {
        return env.VERSION_RC + '+ci.' + env.BUILD_NUMBER
    }
}

void simpleShExecution() {
    sh '''
        git version
    '''
}
